sudo: required
services:
    - docker

before_install:
    - docker build -t alexeyca/docker-react -f Dockerfile.dev .

script:
    - docker run -e CI=true alexeyca/docker-react npm run test -- --coverage